#!/bin/bash

if [[ "$#" < 1 ]]; then
    echo "No argument given. Run './exec help' for options."
fi

for arg in "$@"
do
	if [[ "$arg" == "help" ]]; then
		echo -e "./exec [ setup | build | run | clean | heroku ]"
		echo -e "\t setup - install node dependencies"
		echo -e "\t build - run tsc to populate build/ dir with relevant js and html files."
		echo -e "\t run - run the application"
		echo -e "\t clean - clear all files and directories from build directory"
		echo -e "\t heroku - list heroku relevant commands for server hosting"
	fi

	if [[ "$arg" == "setup" ]] || [[ "$arg" == "install" ]]; then
		npm install
	fi

	if [[ "$arg" == "build" ]]; then
		npm run tsc
		npm run html
	fi

	if [[ "$arg" == "run" ]]; then
	    npm run start
	fi

	if [[ "$arg" == "clean" ]]; then
        rm -r ./build/*
		echo "Deleted all files from build/"
	fi

	if [[ "$arg" == "heroku" ]]; then
		echo -e "\t Deploy locally: heroku local web"
		echo -e "\t Deploy to live: git push heroku master"
		echo -e "\t Scale the app: heroku ps:scale web=0"
		echo -e "\t Visit live: heroku open"
		echo -e "\t View inside dyno: heroku run bash"
		echo -e "\t See config vars: heroku config"
	fi

done
